In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('Datasets/Recommend.csv')
#df

In [3]:
df=pd.read_csv('Datasets/Recommend.csv',names=['user_id','movie_id','rating','timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [4]:
#declare number of users and movies and create a train test split 75/25

n_users=df.user_id.unique().shape[0]
n_movies=df.movie_id.unique().shape[0]
train_data,test_data=train_test_split(df,test_size=0.25)

In [5]:
import numpy as np


In [6]:
train_data_matrix=np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
train_data_matrix

array([[5., 0., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
#Reference Code for matrix
import numpy as np
import pandas as pd

# Example train_data DataFrame
data = {
    'user_id': [1, 1, 2, 2, 3],
    'movie_id': [1, 2, 1, 3, 2],
    'rating': [5, 3, 4, 2, 5]
}
train_data = pd.DataFrame(data)

# Number of unique users and movies
n_users = train_data.user_id.unique().shape[0]
n_movies = train_data.movie_id.unique().shape[0]

# Initialize the user-item matrix
train_data_matrix = np.zeros((n_users, n_movies))

# Populate the matrix with ratings
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

print(train_data_matrix)

[[5. 3. 0.]
 [4. 0. 2.]
 [0. 5. 0.]]


In [ ]:
#Use case solution step 5