In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('Datasets/Recommend.csv')
#df

In [3]:
df=pd.read_csv('Datasets/Recommend.csv',names=['user_id','movie_id','rating','timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [4]:
#declare number of users and movies and create a train test split 75/25

n_users=df.user_id.unique().shape[0]
n_movies=df.movie_id.unique().shape[0]
train_data,test_data=train_test_split(df,test_size=0.25)

In [5]:
import numpy as np


In [6]:
train_data_matrix=np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
train_data_matrix

array([[5., 3., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [7]:
#Reference Code for matrix
import numpy as np
import pandas as pd

# Example train_data DataFrame
data = {
    'user_id': [1, 1, 2, 2, 3],
    'movie_id': [1, 2, 1, 3, 2],
    'rating': [5, 3, 4, 2, 5]
}
train_data = pd.DataFrame(data)

# Number of unique users and movies
n_users = train_data.user_id.unique().shape[0]
n_movies = train_data.movie_id.unique().shape[0]

# Initialize the user-item matrix
train_data_matrix = np.zeros((n_users, n_movies))

# Populate the matrix with ratings
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

print(train_data_matrix)

[[5. 3. 0.]
 [4. 0. 2.]
 [0. 5. 0.]]


In [8]:
#Use case solution step 5

In [9]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')
movie_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')
mean_user_rating=train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff=(train_data_matrix-mean_user_rating)
user_pred=mean_user_rating+user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[2.18916496, 4.27030551, 1.54052953],
       [1.08930542, 4.76635427, 0.14434031],
       [3.7756093 , 0.42926512, 0.79512558]])

In [10]:
# This code implements a user-based collaborative filtering recommendation system. 
# It calculates predicted ratings for users based on the similarities between users and
# the differences between their ratings and their average ratings. 

In [11]:
movie_pred=train_data_matrix.dot(movie_similarity)/np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[1.8434971 , 1.87157107, 3.54577707],
       [0.77100193, 2.74862843, 1.09155414],
       [3.07249517, 0.        , 3.63555733]])

In [18]:
def rmse(pred,test):
    pred=pred[test.nonzero()].flatten()
    test=test[test.nonzero()].flatten()
    return sqrt(mean_squared_error(pred,test))

In [15]:
test_data_matrix=np.zeros((n_users,n_movies))


In [20]:
# Populate the matrix with ratings
for line in train_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]

print(test_data_matrix)

[[5. 3. 0.]
 [4. 0. 2.]
 [0. 5. 0.]]


In [21]:
rmse(user_pred,test_data_matrix)
rmse(movie_pred,test_data_matrix)

NameError: name 'sqrt' is not defined